part refacto
jayk-u/phasing pull request #85
Opened 2021-03-18 13:37 UTC by Peterparcoeur

Petite refacto, encore a ameliorer...

2021-03-19 15:15 UTC, DumontNicolas requested changes
C'est un petit début.
A retravailler.
9/20

2021-03-19 15:15 UTC, DumontNicolas commented on app/javascript/components/cameraOpacity.js
> +const camera = (game, layout, egyptian) => {
plutot character que egyptian

2021-03-19 16:58 UTC, Peterparcoeur commented on app/javascript/components/cameraOpacity.js
> +const camera = (game, layout, egyptian) => {
c'est fait mon pote

2021-03-22 16:01 UTC, DumontNicolas approved these changes

2021-03-22 16:02 UTC, merged